python/wire/wireApp/models.py
# import redis
from . import db
from sqlalchemy import func

# r = redis.Redis(host="redis", port = "6379", db=0)
# r = redis.Redis(host="localhost", port = "6379", db=0)

class Experiment(db.Model):
    __tablename__ = "experiment"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), unique=True)
    date = db.Column(db.Date(), default=func.current_date())
    irradiation_finished = db.Column(db.DateTime(), default=func.now())
    irradiation_time = db.Column(db.Float)
    power = db.Column(db.Float)
    foil_type = db.Column(db.String(20))
    samples = db.relationship('Sample', backref='expermt')

    def __repr__(self):
        return f"{self.__class__.__name__}<{self.name}>"
    
class Sample(db.Model):
    __tablename__ = 'sample'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.Integer, default=0)
    cooling_finished = db.Column(db.DateTime())
    area = db.Column(db.Float)
    cooling_time = db.Column(db.Float)
    measuring_time = db.Column(db.Float)
    mass = db.Column(db.Float)
    activity = db.Column(db.Float)
    exp_id = db.Column(db.Integer, db.ForeignKey("experiment.id"))

    def __repr__(self):
        return f"{self.__class__.__name__}<{self.id}>"

python/wire/wireApp/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from dotenv import load_dotenv

python_folder, _ = os.path.split(os.getcwd())
template_folder_path = os.path.join(python_folder, "templates")
static_folder_path = os.path.join(python_folder, "static", __name__)
template_prefix = __name__

load_dotenv()
#TODO add config file .py 

db = SQLAlchemy()
migrate = Migrate()

def create_app(test_config=None):
    app = Flask(__name__)
    app.config.from_mapping(
        SECRET_KEY = "DEV",
        SQLALCHEMY_DATABASE_URI = f"postgresql+pg8000://{os.environ['PSQL_USER']}:{os.environ['PSWD']}@{os.environ['HOST']}:{os.environ['PORT']}/{os.environ['DB']}",
        # SQLALCHEMY_DATABASE_URI = f"postgresql+pg8000://{os.environ['PSQL_USER']}:{os.environ['PSWD']}@db:5432/{os.environ['DB']}",
        DOWNLOAD_FOLDER = f"{os.path.join(os.getcwd(), 'Downloads')}",
    )
    app.template_folder = template_folder_path
    app._static_folder = static_folder_path
    db.init_app(app)
    migrate.init_app(app, db)
    
    from .views import view
    app.register_blueprint(view, prefix="/")

    return app

python/wire/wireApp/views.py
import xlsxwriter
import os
import time
import requests
from flask import render_template, redirect, url_for, Blueprint, request, send_from_directory
from datetime import timedelta
from . import create_app, template_prefix
from .models import *
from .handler import *
from collections import defaultdict

view = Blueprint('view', __name__)

app = create_app()

@view.route('/add_wire_experiment', methods=["GET", "POST"])
def add_wire_experiment():
    if request.method == "POST":
        name = request.form["Experiment"]
        irr_time  = (conver_datetime(request.form["Irr-finished"]) - conver_datetime(request.form["Irr-started"])).total_seconds()
        date = conver_datetime(request.form["Irr-finished"]).date()
        instance = Experiment(name=name, date=date, irradiation_finished=request.form["Irr-finished"], 
                              irradiation_time=irr_time, power=1, foil_type=request.form["Foil-type"])
        db.session.add(instance)
        db.session.commit()
        return redirect(url_for("view.wire_experiments_list"))
    return render_template(f"{template_prefix}/add-wire-experiment.html")

@view.route("/list_wire_experiments", methods=["GET"])
def wire_experiments_list():
    listed = Experiment.query.all()
    return render_template(f"{template_prefix}/list-wire-experiments.html", list=listed)

@view.route("/wire_experiment/<id>", methods=["GET", "POST"])
def detail_wire_experiment(id):
    # r = requests.get("http://localhost:8080/api/detector_params/nuclide/AU-197") #TODO dont forget to test internal call
    # print(r.json())
    exper_instance = Experiment.query.filter(Experiment.id==int(id)).first()
    irr_fn = exper_instance.irradiation_finished
    irr_time = exper_instance.irradiation_time
    if request.method == "POST":
        sample_name = request.form["Id"]
        A, mass, cool_time, meas_time = activity(net_counts=request.form["Area"], irr_time=irr_time, irr_fn=irr_fn, meas_time=request.form["Meas-time"],
                                            cool_fn=request.form["Cool-finished"], mass=request.form["Mass"], foil_type=exper_instance.foil_type)
        print(A)
        add_sub_instance = Sample(name=sample_name, cooling_finished=request.form["Cool-finished"], area=request.form["Area"], 
                                activity=A, cooling_time=cool_time, measuring_time=meas_time, mass=mass, expermt=exper_instance)
        db.session.add(add_sub_instance)
        print(add_sub_instance)
        db.session.commit()
        return redirect(url_for("view.detail_wire_experiment", id=id))
    return render_template(f"{template_prefix}/wire-experiment.html", data=exper_instance)

@view.route("/edit_wire_experiment/<id>", methods=["GET", "POST"])
def edit_wire_experiment(id):
    exper_instance = Experiment.query.filter(Experiment.id==int(id)).first()
    started_time = exper_instance.irradiation_finished - timedelta(seconds=exper_instance.irradiation_time)
    if request.method == "POST":
        exper_instance.name, exper_instance.irradiation_finished = request.form["Experiment"], request.form["Irr-finished"]
        exper_instance.irradiation_time = (conver_datetime(request.form["Irr-finished"]) - conver_datetime( request.form["Irr-started"])).total_seconds()
        exper_instance.date, exper_instance.foil_type = conver_datetime(request.form["Irr-finished"]).date(), request.form["Foil-type"]
        db.session.commit()
        return redirect(url_for("view.detail_wire_experiment", id=id))
    return render_template(f"{template_prefix}/edit-wire-experiment.html", data=exper_instance, irradiation_started=started_time)

@view.route("/edit_wire_experiment/<id>/<sample_id>", methods=["GET", "POST"])
def edit_wire_sample(id, sample_id):
    sample_instance = Sample.query.join(Experiment).filter(Experiment.id==int(id), Sample.name==int(sample_id)).first()
    if request.method == "POST":
        exper_instance = Experiment.query.filter(Experiment.id==int(id)).first()
        irr_fn = exper_instance.irradiation_finished
        irr_time = exper_instance.irradiation_time
        A, mass, cool_time, meas_time = activity(net_counts=request.form["Area"], irr_time=irr_time, irr_fn=irr_fn, 
                                                 meas_time=request.form["Meas-time"],cool_fn=request.form["Cool-finished"], 
                                                 mass=request.form["Mass"], foil_type=exper_instance.foil_type)
        sample_instance.cooling_finished, sample_instance.area, sample_instance.cooling_time = request.form["Cool-finished"], request.form["Area"], cool_time
        sample_instance.measuring_time, sample_instance.mass, sample_instance.activity = meas_time, mass, A
        sample_instance.name = request.form["Id"]
        db.session.flush()
        db.session.commit()
        return redirect(url_for("view.detail_wire_experiment", id=id))
    return render_template(f"{template_prefix}/edit-wire-sample.html", data=sample_instance)

@view.route("/<name>/export", methods=["GET","POST"])
def export_wire_experiment(name):
    if request.method == "POST":
        dct = defaultdict(list)
        instance = Experiment.query.filter(Experiment.name==name).first()
        dct['irradiation_finished'].append(instance.irradiation_finished)
        dct['irradiation_time'].append(instance.irradiation_time)
        for n, i in enumerate(instance.samples):
            dct["id"].append(i.id)
            dct["cooling_finished"].append(i.cooling_finished)
            dct["cooling_time"].append(i.cooling_time)
            dct["measuring_time"].append(i.measuring_time)
            dct["mass"].append(i.mass)
            dct["area"].append(i.area)
            dct["activity"].append(i.activity)
        try:
            os.mkdir(os.path.join(os.getcwd(), "Downloads"))
        except FileExistsError as e:
            print(e)
        with xlsxwriter.Workbook(os.path.join(app.config["DOWNLOAD_FOLDER"], "export.xlsx")) as wb:
            wsh = wb.add_worksheet()
            header = ["IrrFinished", "IrrTime", "ID", "CoolFinished", "CoolTime", "MeasTime", "Mass", "NetCounts", "Activity"]
            header_format = wb.add_format({ 'bold': True,
                                            'bottom': 2,
                                            'bg_color': '#F9DA04'})
            datetime_format = wb.add_format({'num_format': 'dd/mm/yy hh:mm'})
            for n, i in enumerate(header, start=1):
                wsh.write(1, n, i, header_format)
            for num, i in enumerate(dct.values(), start=1):
                if not isinstance(i[0], datetime):
                    wsh.write_column(2, num, i)
                else:
                    wsh.write_column(2, num, i, datetime_format)
        return send_from_directory(app.config["DOWNLOAD_FOLDER"], "export.xlsx", as_attachment=True)

@view.route("/<id>/delete", methods=["GET","POST"])
def delete_wire_experiment(name):
    if request.method == "POST":
        instance = Experiment.query.filter(Experiment.id==int(id)).first()
        db.session.delete(instance)
        print(instance)
        db.session.commit()
        return redirect(url_for("view.wire_experiments_list"))

@view.route("/<id>/<sample_id>/delete", methods=["GET","POST"])
def delete_wire_sample(id, sample_id):
    if request.method == "POST":
        sample_instance = Sample.query.join(Experiment).filter(Experiment.id==int(id), Sample.name==int(sample_id)).first()
        db.session.delete(sample_instance)
        print(sample_instance)
        db.session.commit()
        return redirect(url_for("view.wire_experiments_list"))

python/templates/wireApp/add-experiment.html
{% extends 'base.html' %}
	{% block title %}
	<title> Home Page </title>
	{% endblock %}
	{% block content %}
		<form method="POST", enctype="multipart/form-data"> 
			<div class='main-box'>
				<div class="card text-center">
				  <div class="card-header">
				    Experiment setting up
				  </div>
				  <div class="card-body">
				    <h5 class="card-title">Fill the forms below</h5> <br>
					<!--* add container here -->
					<div class="container">
						<div class="row">
							<div class="col" style="width:50%">
								<label for="Experiment" class="form-label">Experiment name</label>
								<input name="Experiment" class="form-control" type="text">
							  </div>
						</div>
						<br>
						<div class="row">
						  <div class="col" style="width:50%">
							<label for="Irr-started" class="form-label">Irradiation started</label>
							<input name="Irr-started" class="form-control" type="datetime-local">
						  </div>
						  <div class="col" style="width:50%">
							<label for="Irr-finished" class="form-label">Irradiation finished</label>
							<input name="Irr-finished" class="form-control" type="datetime-local">
						  </div>
						</div>
						<br>
					</div>
					<br>
				    <input type="submit" class="btn btn-primary">
				  </div>
				</div>
			</div>
		</form>
	{% endblock %}

python/templates/wireApp/edit-experiment.html
{% extends 'base.html' %}
	{% block title %}
	<title> Home Page </title>
	{% endblock %}
	{% block content %}
		<form method="POST", enctype="multipart/form-data"> 
			<div class='main-box'>
				<div class="card text-center">
				  <div class="card-header">
				    Experiment setting up
				  </div>
				  <div class="card-body">
				    <h5 class="card-title">Fill the forms below</h5> <br>
					<!--* add container here -->
					<div class="container">
						<div class="row">
							<div class="col" style="width:50%">
								<label for="Experiment" class="form-label">Experiment name</label>
								<input name="Experiment" class="form-control" type="text" value="{{data.name}}">
							  </div>
						</div>
						<br>
						<div class="row">
						  <div class="col" style="width:50%">
							<label for="Irr-started" class="form-label">Irradiation started</label>
							<input name="Irr-started" class="form-control" type="datetime-local" value="{{irradiation_started.strftime('%Y-%m-%dT%H:%M')}}">
						  </div>
						  <div class="col" style="width:50%">
							<label for="Irr-finished" class="form-label">Irradiation finished</label>
							<input name="Irr-finished" class="form-control" type="datetime-local" value="{{data.irradiation_finished.strftime('%Y-%m-%dT%H:%M')}}">
						  </div>
						</div>
						<br>
					</div>
					<br>
				    <input type="submit" class="btn btn-primary">
				  </div>
				</div>
			</div>
		</form>
	{% endblock %}

python/templates/wireApp/edit-sample.html
{% extends 'base.html' %}
	{% block title %}
	<title> Edit Sample </title>
	{% endblock %}
	{% block content %}
		<form method="POST", enctype="multipart/form-data"> 
			<div class='main-box'>
				<div class="card text-center">
				  <div class="card-header">
				    Editing sample ID={{data.id}}
				  </div>
				  <div class="card-body">
					<br>
				    <h5 class="card-title">Change and commit</h5> <br>
					<!--* add container here -->
					<div class="container">
						<div class="row">
							<div class="col" style="width:50%">
								<label for="Id" class="form-label">ID</label>
								<input name="Id" class="form-control" type="number" step="1" value="{{data.name}}">
							  </div>
							<div class="col" style="width:50%">
							  <label for="Area" class="form-label">Area</label>
							  <input name="Area" class="form-control" type="number" step="1" value="{{data.area}}">
							</div>
						</div>
						<br>
						<br>
						<div class="row">
							<div class="col" style="width:50%">
							  <label for="Cool-finished" class="form-label">Cooling finished</label>
							  <input name="Cool-finished" class="form-control" type="datetime-local" value="{{data.cooling_finished.strftime('%Y-%m-%dT%H:%M')}}">
							</div>
							<div class="col" style="width:50%">
								<label for="Meas-time" class="form-label">Measuring time</label>
								<input name="Meas-time" class="form-control" type="number" step="1" value="{{data.measuring_time}}">
							</div>
						</div>
						<br>
						<div class="row">
							<div class="col" style="width:50%">
							  <label for="Foil-type" class="form-label">Foil type</label>
							  <select name="Foil-type" class="form-select" aria-label="Default select example">
								<option selected value="1">One</option>
								<option value="2">Two</option>
								<option value="3">Three</option>
							  </select>
							</div>
							<div class="col" style="width:50%">
							  <label for="Mass" class="form-label">Mass</label>
							  <input name="Mass" class="form-control" type="number" step="0.0001" value="{{data.mass}}">
							</div>
						</div>
					</div>
					<br>
				    <input type="submit" class="btn btn-primary" value="Commit">
				  </div>
				  <div class="card-footer text-muted">
					Click <a href="#" data-bs-toggle="modal" data-bs-target="#deleteModal"> here </a> to delete experiment
				  </div>
				</div>
			</div>
		</form>
		<br>
		<br>
		<form action='{{url_for("view.delete_experiment", name=data.name)}}' method="POST", enctype="multipart/form-data">
			<!-- Modal -->
			<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
						<h5 class="modal-title" id="deleteModalLabel">Are you sure on deleting refueling instance?</h5>
						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
						</div>
						<div class="modal-body">
							All data of sample {{data.id}} will be deleted!
						</div>
						<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
						<button type="submit" class="btn btn-danger">Delete!</button>
						</div>
					</div>
				</div>
			</div>
		</form>
	{% endblock %}

python/templates/wireApp/edit-wire-sample.html
{% extends 'base.html' %}
	{% block title %}
	<title> Edit Sample </title>
	{% endblock %}
	{% block content %}
		<form method="POST", enctype="multipart/form-data"> 
			<div class='main-box'>
				<div class="card text-center">
				  <div class="card-header">
				    Editing sample ID={{data.id}}
				  </div>
				  <div class="card-body">
					<br>
				    <h5 class="card-title">Change and commit</h5> <br>
					<!--* add container here -->
					<div class="container">
						<div class="row">
							<div class="col" style="width:50%">
								<label for="Id" class="form-label">ID</label>
								<input name="Id" class="form-control" type="number" step="1" value="{{data.name}}">
							  </div>
							<div class="col" style="width:50%">
							  <label for="Area" class="form-label">Area</label>
							  <input name="Area" class="form-control" type="number" step="1" value="{{data.area}}">
							</div>
						</div>
						<br>
						<br>
						<div class="row">
							<div class="col" style="width:50%">
							  <label for="Cool-finished" class="form-label">Cooling finished</label>
							  <input name="Cool-finished" class="form-control" type="datetime-local" value="{{data.cooling_finished.strftime('%Y-%m-%dT%H:%M')}}">
							</div>
							<div class="col" style="width:50%">
								<label for="Meas-time" class="form-label">Measuring time</label>
								<input name="Meas-time" class="form-control" type="number" step="1" value="{{data.measuring_time}}">
							</div>
						</div>
						<br>
						<div class="row">
							<div class="col" style="width:50%">
								<label for="Mass" class="form-label">Mass</label>
								<input name="Mass" class="form-control" type="number" value="{{data.mass}}">
							  </div>
							<div class="col" style="width:50%">
							</div>
							
						</div>
					</div>
					<br>
				    <input type="submit" class="btn btn-primary" value="Commit">
				  </div>
				  <div class="card-footer text-muted">
					Click <a href="#" data-bs-toggle="modal" data-bs-target="#deleteModal"> here </a> to delete samle
				  </div>
				</div>
			</div>
		</form>
		<br>
		<br>
		<form action='{{url_for("view.delete_wire_sample", id=data.exp_id, sample_id=data.id)}}' method="POST", enctype="multipart/form-data">
			<!-- Modal -->
			<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
						<h5 class="modal-title" id="deleteModalLabel">Are you sure on deleting refueling instance?</h5>
						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
						</div>
						<div class="modal-body">
							All data of sample {{data.id}} will be deleted!
						</div>
						<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
						<button type="submit" class="btn btn-danger">Delete!</button>
						</div>
					</div>
				</div>
			</div>
		</form>
	{% endblock %}

python/templates/wireApp/list-wire-experiments.html
{% extends 'base.html' %}
	{% block title %}
	<title> List Page </title>
	{% endblock %}

{% block content %}
<div class="container">
<div class="row align-items-center">
	<div class="row">
		{% for i in list %}
			<div class="col">
				<div class="card text-center" style="width: 350px; margin:auto">
					<!-- <img src="..." class="card-img-top" alt="..."> -->
					<p class="card-title">{{i.date}}</p>
					<div class="card-body">
						<h5 class="card-title">{{i.name}}</h5>
						<p class="card-text"> There are {{i.samples| length}} samples here</p>
						<a href="{{url_for('view.detail_wire_experiment', id=i.id)}}" class="btn btn-primary">View</a>
					</div>
				</div>
				<br>
			</div>
		{% endfor %}
	</div>
</div>
</div>
{% endblock %}

python/templates/wireApp/list.html
{% extends 'base.html' %}
	{% block title %}
	<title> List Page </title>
	{% endblock %}

{% block content %}
<div class="container">
<div class="row align-items-center">
	<div class="row">
		{% for i in list %}
			<div class="col">
				<div class="card text-center" style="width: 350px; margin:auto">
					<!-- <img src="..." class="card-img-top" alt="..."> -->
					<p class="card-title">{{i.date}}</p>
					<div class="card-body">
						<h5 class="card-title">{{i.name}}</h5>
						<p class="card-text"> There are {{i.samples| length}} samples here</p>
						<a href="{{url_for('view.detail', id=i.id)}}" class="btn btn-primary">View</a>
					</div>
				</div>
				<br>
			</div>
		{% endfor %}
	</div>
</div>
</div>
{% endblock %}

python/templates/wireApp/wire-experiment.html
{% extends 'base.html' %}
	{% block title %}
	<title> Experiment </title>
	{% endblock %}
	{% block content %}
		<form method="POST", enctype="multipart/form-data"> 
			<div class='main-box'>
				<div class="card text-center">
				  <div class="card-header">
				    {{data.name}} from {{data.date}}
				  </div>
				  <div class="card-body">
					<div class="container">
						<div class="row">
							<div class="col" style="width:50%">
								<p class="form-label">Reactor power</p>
							</div>
							<div class="col" style="width:50%">
								<p class="form-label">Irradiation time</p>
							</div>
							<div class="col" style="width:50%">
								<p class="form-label">Foil type</p>
							</div>
						</div>
						<div class="row">
							<div class="col" style="width:50%">
								<label class="form-label">{{data.power}}</label>
							</div>
							<div class="col" style="width:50%">
								<label class="form-label">{{data.irradiation_time}}</label>
							</div>
							<div class="col" style="width:50%">
								<label class="form-label">{{data.foil_type}}</label>
							</div>
						</div>
						<div class="row">
							<div class="col" style="width:50%">
								<a href="{{url_for('view.edit_wire_experiment', id=data.id)}}" class="btn btn-primary">Edit</a>
							</div>
						</div>
					</div>
					<br>
				    <h5 class="card-title">Fill the forms below to add new sample</h5> <br>
					<!--* add container here -->
					<div class="container">
						<div class="row">
							<div class="col" style="width:50%">
								<label for="Id" class="form-label">ID</label>
								<input name="Id" class="form-control" type="number" step="1">
							  </div>
							<div class="col" style="width:50%">
							  <label for="Area" class="form-label">Area</label>
							  <input name="Area" class="form-control" type="number" step="1">
							</div>
						</div>
						<br>
						<br>
						<div class="row">
							<div class="col" style="width:50%">
							  <label for="Cool-finished" class="form-label">Cooling finished</label>
							  <input name="Cool-finished" class="form-control" type="datetime-local" value="{{data.date.strftime('%Y-%m-%dT%H:%M')}}">
							</div>
							<div class="col" style="width:50%">
								<label for="Meas-time" class="form-label">Measuring time</label>
								<input name="Meas-time" class="form-control" type="number" step="1">
							</div>
						</div>
						<br>
						<div class="row">
							<div class="col" style="width:50%">
								<label for="Mass" class="form-label">Mass</label>
								<input name="Mass" class="form-control" type="number">
							</div>
							<div class="col" style="width:50%">
							  <!-- <label for="Foil-type" class="form-label">Foil type</label>
							  <select name="Foil-type" class="form-select" aria-label="Default select example">
								<option selected value="1">One</option>
								<option value="2">Two</option>
								<option value="3">Three</option>
							  </select> -->
							</div>
						</div>
					</div>
					<br>
				    <input type="submit" class="btn btn-primary">
				  </div>
				  <div class="card-footer text-muted">
					Click <a href="#" data-bs-toggle="modal" data-bs-target="#deleteModal"> here </a> to delete experiment
				  </div>
				</div>
			</div>
		</form>
		<br>
		<br>
		<div class="samples-box">
			<div class='row'>
				<div class='col center-text'>
					<form action='{{url_for("view.export_wire_experiment", name=data.name)}}' method="POST", enctype="multipart/form-data"> 
						<input type="submit" class="btn btn-primary" value="Export to .xlsx"> <br> <br>
						<a href="http://localhost:8080/api/experiment/{{data.id}}" class="btn btn-primary">Go to API</a>
					</form>
				</div>
			</div>
			<br>
			<div class='row'>
				<div class='col center-text'>
					<table class="table">
						<thead>
						  <tr>
							<th scope="col">ID</th>
							<th scope="col">Mass</th>
							<th scope="col">Activity</th>
							<th scope="col">Link</th>
						  </tr>
						</thead>
						<tbody>
						{% for i in data.samples | sort(attribute="id") %}
						  <tr>
							<th scope="row">{{i.name}}</th>
							<td>{{i.mass}}</td>
							<td>{{'%0.2e' % i.activity}}</td>
							<td><a href="{{url_for('view.edit_wire_sample', id=data.id, sample_id=i.name)}}">Edit</a></td>
						  </tr>
						</tbody>
						{% endfor %}
					  </table>
				</div>
				<div class='col center-text'>
					<canvas id="myChart" width="400" height="400"></canvas>
				</div>
		</div>
		<form action='{{url_for("view.delete_wire_experiment", id=data.id)}}' method="POST", enctype="multipart/form-data">
			<!-- Modal -->
			<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
						<h5 class="modal-title" id="deleteModalLabel">Are you sure on deleting instance?</h5>
						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
						</div>
						<div class="modal-body">
							All data of {{data.name}} including {{data.samples|length}} sample(s) will be deleted!
						</div>
						<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
						<button type="submit" class="btn btn-danger">Delete!</button>
						</div>
					</div>
				</div>
			</div>
		</form>
		</div>
		<script src="{{url_for('static', filename='chart.js')}}"></script>
	{% endblock %}