python-app/wireApp/__init__.py
import os
from flask import Flask, Blueprint
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from dotenv import load_dotenv



load_dotenv()

#TODO add config file .py 

db = SQLAlchemy()
migrate = Migrate()

def create_app(test_config=None):
    app = Flask(__name__)
    app.config.from_mapping(
        SECRET_KEY = "DEV",
        SQLALCHEMY_DATABASE_URI = f"postgresql+pg8000://{os.environ['PSQL_USER']}:{os.environ['PSWD']}@{os.environ['HOST']}:{os.environ['PORT']}/{os.environ['DB']}",
        # SQLALCHEMY_DATABASE_URI = f"postgresql+pg8000://{os.environ['PSQL_USER']}:{os.environ['PSWD']}@db:5432/{os.environ['DB']}",
        DOWNLOAD_FOLDER = f"{os.path.join(os.getcwd(), 'Downloads')}"
    )
    db.init_app(app)
    migrate.init_app(app, db)
    

    from .views import view
    # from .api import api5
    app.register_blueprint(view, prefix="/")
    # app.register_blueprint(api, prefix="/api")
    # app.register_blueprint(api_bp, prefix="/")
    # if test_config is None:
    #     # load the instance config, if it exists, when not testing
    #     app.config.from_pyfile('config.py', silent=True)
    # else:
    #     # load the test config if passed in
    #     app.config.from_mapping(test_config)
    return app

python-app/wireApp/views.py
import xlsxwriter
import os
from flask import render_template, redirect, url_for, Blueprint, request, send_from_directory
from datetime import timedelta
from . import create_app
from .model import *
from .handler import *
from collections import defaultdict

view = Blueprint('view', __name__)

app = create_app()

@view.route('/create', methods=["GET", "POST"])
def create():
    if request.method == "POST":
        name = request.form["Experiment"]
        irr_time  = (conver_datetime(request.form["Irr-finished"]) - conver_datetime(request.form["Irr-started"])).total_seconds()
        date = conver_datetime(request.form["Irr-finished"]).date()
        instance = Experiment(name=name, date=date, irradiation_finished=request.form["Irr-finished"], irradiation_time=irr_time, power=1)
        db.session.add(instance)
        db.session.commit()
        return redirect(url_for("view.experiments_list"))
    return render_template("add-experiment.html")

@view.route("/list", methods=["GET"])
def experiments_list():
    listed = Experiment.query.all()
    return render_template("list.html", list=listed)


@view.route("/experiment/<id>", methods=["GET", "POST"])
def detail(id):
    exper_instance = Experiment.query.filter(Experiment.id==int(id)).first()
    irr_fn = exper_instance.irradiation_finished
    irr_time = exper_instance.irradiation_time
    if request.method == "POST":
        sample_name = request.form["Id"]
        A, mass, cool_time, meas_time = activity(net_counts=request.form["Area"], irr_time=irr_time, irr_fn=irr_fn, meas_time=request.form["Meas-time"],
                                            cool_fn=request.form["Cool-finished"], mass=request.form["Mass"])
        print(A)
        add_sub_instance = Sample(name=sample_name, cooling_finished=request.form["Cool-finished"], area=request.form["Area"], 
                                activity=A, cooling_time=cool_time, measuring_time=meas_time, mass=mass, expermt=exper_instance)
        db.session.add(add_sub_instance)
        print(add_sub_instance)
        db.session.commit()
        return redirect(url_for("view.detail", id=id))
    return render_template("experiment.html", data=exper_instance)

@view.route("/edit/<name>", methods=["GET", "POST"])
def edit_experiment(name):
    exper_instance = Experiment.query.filter(Experiment.name==name).first()
    
    started_time = exper_instance.irradiation_finished - timedelta(seconds=exper_instance.irradiation_time)
    if request.method == "POST":
        exper_instance.name, exper_instance.irradiation_finished = request.form["Experiment"], request.form["Irr-finished"]
        exper_instance.irradiation_time = (conver_datetime(request.form["Irr-finished"]) - conver_datetime( request.form["Irr-started"])).total_seconds()
        exper_instance.date = conver_datetime(request.form["Irr-finished"]).date()
        db.session.commit()
        return redirect(url_for("view.detail", name=name))
    return render_template("edit-experiment.html", data=exper_instance, irradiation_started=started_time)

@view.route("/edit/<name>/<sample_id>/", methods=["GET", "POST"])
def edit_sample(name, sample_id):
    sample_instance = Sample.query.join(Experiment).filter(Experiment.name==name, Sample.name==int(sample_id)).first()
    print(sample_instance.cooling_finished)
    if request.method == "POST":
        exper_instance = Experiment.query.filter(Experiment.name==name).first()
        irr_fn = exper_instance.irradiation_finished
        irr_time = exper_instance.irradiation_time
        A, mass, cool_time, meas_time = activity(net_counts=request.form["Area"], irr_time=irr_time, irr_fn=irr_fn, meas_time=request.form["Meas-time"],
                                                 cool_fn=request.form["Cool-finished"], mass=request.form["Mass"])
        sample_instance.cooling_finished, sample_instance.area, sample_instance.cooling_time = request.form["Cool-finished"], request.form["Area"], cool_time
        sample_instance.measuring_time, sample_instance.mass, sample_instance.activity = meas_time, mass, A
        sample_instance.name = request.form["Id"]
        db.session.flush()
        db.session.commit()
        return redirect(url_for("view.detail", name=name))
    return render_template("edit-sample.html", data=sample_instance)

@view.route("/<name>/export", methods=["GET","POST"])
def export_experiment(name):
    if request.method == "POST":
        dct = defaultdict(list)
        instance = Experiment.query.filter(Experiment.name==name).first()
        dct['irradiation_finished'].append(instance.irradiation_finished)
        dct['irradiation_time'].append(instance.irradiation_time)
        for n, i in enumerate(instance.samples):
            dct["id"].append(i.id)
            dct["cooling_finished"].append(i.cooling_finished)
            dct["cooling_time"].append(i.cooling_time)
            dct["measuring_time"].append(i.measuring_time)
            dct["mass"].append(i.mass)
            dct["area"].append(i.area)
            dct["activity"].append(i.activity)
        try:
            os.mkdir(os.path.join(os.getcwd(), "Downloads"))
        except FileExistsError as e:
            print(e)
        with xlsxwriter.Workbook(os.path.join(app.config["DOWNLOAD_FOLDER"], "export.xlsx")) as wb:
            wsh = wb.add_worksheet()
            header = ["IrrFinished", "IrrTime", "ID", "CoolFinished", "CoolTime", "MeasTime", "Mass", "NetCounts", "Activity"]
            header_format = wb.add_format({ 'bold': True,
                                            'bottom': 2,
                                            'bg_color': '#F9DA04'})
            datetime_format = wb.add_format({'num_format': 'dd/mm/yy hh:mm'})
            for n, i in enumerate(header, start=1):
                wsh.write(1, n, i, header_format)
            for num, i in enumerate(dct.values(), start=1):
                if not isinstance(i[0], datetime):
                    wsh.write_column(2, num, i)
                else:
                    wsh.write_column(2, num, i, datetime_format)
        return send_from_directory(app.config["DOWNLOAD_FOLDER"], "export.xlsx", as_attachment=True)

@view.route("/<name>/delete", methods=["GET","POST"])
def delete_experiment(name):
    if request.method == "POST":
        instance = Experiment.query.filter(Experiment.name==name).first()
        db.session.delete(instance)
        print(instance)
        db.session.commit()
        return redirect(url_for("view.experiments_list"))

python-app/wireApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='style.css')}}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.6.0/chart.min.js" integrity="sha512-GMGzUEevhWh8Tc/njS0bDpwgxdCJLQBWG3Z2Ct+JGOpVnEmjvNx6ts4v6A2XJf1HOrtOsfhv3hBKpK9kE5z8AQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	{% block title %}
	
	{% endblock %}
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	  <div class="container-fluid">
	    <a class="navbar-brand" href="#">IRT-T</a>
	    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
	      <span class="navbar-toggler-icon"></span>
	    </button>
	    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
	      <div class="navbar-nav">
	        <a class="nav-link active" aria-current="page" href='{{url_for("view.create")}}'>Create</a>
	        <a class="nav-link active" href='{{url_for("view.experiments_list")}}'>List</a>
	      </div>
	    </div>
	  </div>
	</nav>
	<div style="height:50px"> </div>
	{% block content %}

	{% endblock %}

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

python-app/wireApp/templates/experiment.html
{% extends 'base.html' %}
	{% block title %}
	<title> Experiment </title>
	{% endblock %}
	{% block content %}
		<form method="POST", enctype="multipart/form-data"> 
			<div class='main-box'>
				<div class="card text-center">
				  <div class="card-header">
				    {{data.name}} from {{data.date}}
				  </div>
				  <div class="card-body">
					<div class="container">
						<div class="row">
							<div class="col" style="width:50%">
								<p class="form-label">Reactor power</p>
							</div>
							<div class="col" style="width:50%">
								<p class="form-label">Irradiation time</p>
							</div>
						</div>
						<div class="row">
							<div class="col" style="width:50%">
								<label class="form-label">{{data.power}}</label>
							</div>
							<div class="col" style="width:50%">
								<label class="form-label">{{data.irradiation_time}}</label>
							</div>
						</div>
						<div class="row">
							<div class="col" style="width:50%">
								<a href="{{url_for('view.edit_experiment', name=data.name)}}" class="btn btn-primary">Edit</a>
							</div>
						</div>
					</div>
					<br>
				    <h5 class="card-title">Fill the forms below to add new sample</h5> <br>
					<!--* add container here -->
					<div class="container">
						<div class="row">
							<div class="col" style="width:50%">
								<label for="Id" class="form-label">ID</label>
								<input name="Id" class="form-control" type="number" step="1">
							  </div>
							<div class="col" style="width:50%">
							  <label for="Area" class="form-label">Area</label>
							  <input name="Area" class="form-control" type="number" step="1">
							</div>
						</div>
						<br>
						<br>
						<div class="row">
							<div class="col" style="width:50%">
							  <label for="Cool-finished" class="form-label">Cooling finished</label>
							  <input name="Cool-finished" class="form-control" type="datetime-local" value="{{data.date.strftime('%Y-%m-%dT%H:%M')}}">
							</div>
							<div class="col" style="width:50%">
								<label for="Meas-time" class="form-label">Measuring time</label>
								<input name="Meas-time" class="form-control" type="number" step="1">
							</div>
						</div>
						<br>
						<div class="row">
							<div class="col" style="width:50%">
							  <label for="Foil-type" class="form-label">Foil type</label>
							  <select name="Foil-type" class="form-select" aria-label="Default select example">
								<option selected value="1">One</option>
								<option value="2">Two</option>
								<option value="3">Three</option>
							  </select>
							</div>
							<div class="col" style="width:50%">
							  <label for="Mass" class="form-label">Mass</label>
							  <input name="Mass" class="form-control" type="number" step="0.0001">
							</div>
						</div>
					</div>
					<br>
				    <input type="submit" class="btn btn-primary">
				  </div>
				  <div class="card-footer text-muted">
					Click <a href="#" data-bs-toggle="modal" data-bs-target="#deleteModal"> here </a> to delete experiment
				  </div>
				</div>
			</div>
		</form>
		<br>
		<br>
		<div class="samples-box">
			<div class='row'>
				<div class='col center-text'>
					<form action='{{url_for("view.export_experiment", name=data.name)}}' method="POST", enctype="multipart/form-data"> 
						<input type="submit" class="btn btn-primary" value="Export to .xlsx"> <br> <br>
						<a href="http://localhost:8080" class="btn btn-primary">Go to API</a>
					</form>
				</div>
			</div>
			<br>
			<div class='row'>
				<div class='col center-text'>
					<table class="table">
						<thead>
						  <tr>
							<th scope="col">ID</th>
							<th scope="col">Mass</th>
							<th scope="col">Activity</th>
							<th scope="col">Link</th>
						  </tr>
						</thead>
						<tbody>
						{% for i in data.samples | sort(attribute="id") %}
						  <tr>
							<th scope="row">{{i.name}}</th>
							<td>{{i.mass}}</td>
							<td>{{'%0.2e' % i.activity}}</td>
							<td><a href="{{url_for('view.edit_sample', name=data.name, sample_id=i.name)}}">Edit</a></td>
						  </tr>
						</tbody>
						{% endfor %}
					  </table>
				</div>
				<div class='col center-text'>
					<canvas id="myChart" width="400" height="400"></canvas>
				</div>
		</div>
		<form action='{{url_for("view.delete_experiment", name=data.name)}}' method="POST", enctype="multipart/form-data">
			<!-- Modal -->
			<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
				<div class="modal-dialog">
					<div class="modal-content">
						<div class="modal-header">
						<h5 class="modal-title" id="deleteModalLabel">Are you sure on deleting refueling instance?</h5>
						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
						</div>
						<div class="modal-body">
							All data of {{data.name}} including {{data.samples|length}} sample(s) will be deleted!
						</div>
						<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
						<button type="submit" class="btn btn-danger">Delete!</button>
						</div>
					</div>
				</div>
			</div>
		</form>
		</div>
		<script src="{{url_for('static', filename='chart.js')}}"></script>
			
		</script>
	{% endblock %}